name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  natives:
    name: Natives for ${{ matrix.ident }}
    uses: ./.github/workflows/natives.yml
    strategy:
      fail-fast: false
      matrix:
        include:
          - ident: linux-x64
            runner: ubuntu-22.04
          - ident: linux-arm64
            runner: ubuntu-22.04-arm
          - ident: mac-x64
            runner: macos-15-intel
          - ident: mac-arm64
            runner: macos-15
          - ident: win-x64
            runner: windows-2022
    with:
      ident: ${{ matrix.ident }}
      runner: ${{ matrix.runner }}

  assemble:
    name: Assemble
    needs: natives
    uses: ./.github/workflows/assemble.yml
