name: Publish

on:
  release:
    types: [ published ]

jobs:
  natives:
    name: Natives for ${{ matrix.ident }}
    uses: ./.github/workflows/natives.yml
    strategy:
      matrix:
        include:
          - ident: linux-x64
            runner: ubuntu-22.04
          - ident: mac-arm64
            runner: macos-15
          - ident: win-x64
            runner: windows-2022
    with:
      ident: ${{ matrix.ident }}
      runner: ${{ matrix.runner }}

  publish:
    name: Publish
    needs: natives
    uses: ./.github/workflows/assemble.yml
    with:
      version: ${{ github.event.release.tag_name }}
      publish: true
    secrets:
      MAVEN_TOKEN_NAME: ${{ secrets.MAVEN_TOKEN_NAME }}
      MAVEN_TOKEN_SECRET: ${{ secrets.MAVEN_TOKEN_SECRET }}
